### ISSUE TITLE
Setup Github Actions

### ISSUE THREAD

**Issue by tarikeshaq** [ubclaunchpad/news-sentiment#7]
## What is it?
Set up some basic Github Actions that can help us keep CI on our Go code

### What you should do
Read up on Github Actions, and create a simple `go.yml` file that would run on a go code base

### Resources
- Github Actions docs: https://docs.github.com/en/free-pro-team@latest/actions
- Github Actions for Go: https://github.com/actions/starter-workflows/blob/48d91f58fdbd01a65b0e1e4dcc0eda76d3540536/ci/go.yml

## Deliverables:
- A simple Go Github Action setup to run against our upcoming go code. Feel free to initialize a dummy go codebase as you set that up. Create a PR for the action
- Read up on github actions, I have a feeling we might end up using it for deployment too.

**Comment by bobheadxi** [comment]
The Go template for GitHub actions is not really what I see in realistic environments - you might want to refer to something like Inertia as well:

https://github.com/ubclaunchpad/inertia/blob/master/.github/workflows/pipeline.yml#L58-L72

(the linked part is the Windows tests because the other Inertia tests are a lot more complicated, but this is a good starting point, and it includes code coverage reporting)

for more complete examples you can also check out what other projects out in the wild use: https://sourcegraph.com/search?q=repogroup:golang+lang:yaml+uses:+actions/setup-go%40v1+&patternType=literal

**Comment by tarikeshaq** [comment]
Closed by #40
